apps/web/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url('^browse/$', views.BrowseView.as_view(), name='browse'),
    url('^annotate/$', views.AnnotateView.as_view(), name='annotate'),
    url('^submit/$', views.SubmitView.as_view(), name='submit'),
]

code_annotate/urls.py
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings
import django.views.static
from django.views.generic.base import RedirectView

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.web.urls', namespace='web')),
    url(r'^$', RedirectView.as_view(url='/browse/?path=/')),
]

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', django.views.static.serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ] + staticfiles_urlpatterns() + urlpatterns

apps/web/models.py
from django.db import models
from django.conf import settings


class CodeAnnotation(models.Model):
    path = models.CharField(max_length=5000)
    line_number = models.PositiveIntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    annotation = models.TextField()

    def __str__(self):
        return '{}: {}'.format(self.path, self.line_number)

apps/web/views.py
import os
from fnmatch import fnmatch
from operator import itemgetter

from django.conf import settings
from django.core.urlresolvers import reverse
from django.http.response import Http404
from django.shortcuts import redirect
from django.views.generic import TemplateView, CreateView

from pygments import highlight
from pygments.lexers import get_lexer_for_filename
from pygments.formatters.html import HtmlFormatter
from pygments.lexers.special import TextLexer
from pygments.util import ClassNotFound

from apps.web.models import CodeAnnotation


class BaseView(TemplateView):
    def get_breadcrumbs(self, path):
        breadcrumbs = [{'path': '/', 'name': 'Root'}]
        if path != '':
            current_path = ''
            for split in path[1:].split('/'):
                current_path += '/' + split
                breadcrumbs.append({'path': current_path, 'name': split})
        return breadcrumbs


class BrowseView(BaseView):
    template_name = 'web/browse.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        code_directory = os.path.realpath(settings.CODE_DIRECTORY) + os.path.sep
        absolute_path = self.request.GET.get('path')
        if not absolute_path:
            return redirect(reverse('web:browse') + '?path=/')
        if not absolute_path.startswith('/'):
            raise Http404
        absolute_path = '.' + absolute_path
        absolute_path = os.path.join(settings.CODE_DIRECTORY, absolute_path)
        absolute_path = os.path.realpath(absolute_path) + os.path.sep

        if not absolute_path.startswith(code_directory):
            raise Http404

        if not os.path.exists(absolute_path):
            raise Http404

        if not os.path.isdir(absolute_path):
            raise Http404

        relative_path = '/' + absolute_path[len(code_directory):]
        breadcrumbs = self.get_breadcrumbs(relative_path[:-1])

        parent_directory = os.path.realpath(os.path.join(absolute_path, os.path.pardir)) + os.path.sep
        parent_directory = '/' + parent_directory[len(code_directory):]

        files, directories = self.get_files_directories(absolute_path, relative_path)

        context.update({
            'files': files,
            'directories': directories,
            'relative_path': relative_path,
            'parent_directory': parent_directory,
            'breadcrumbs': breadcrumbs,
        })
        return self.render_to_response(context)

    def get_files_directories(self, absolute_path, relative_path):
        directories = []
        files = []

        annotations = set(CodeAnnotation.objects.values_list('path', flat=True).distinct())

        everything = os.listdir(absolute_path)
        everything = (n for n in everything if not any(fnmatch(n, ignore) for ignore in settings.FILE_EXCLUDE_PATTERNS))

        for f in everything:
            path = os.path.join(absolute_path, f)
            rel_path = relative_path + f
            if os.path.isdir(path):
                has_annotations = any(annotation.startswith(rel_path) for annotation in annotations)
                directories.append({'directory': f, 'has_annotations': has_annotations})
            else:
                files.append({'file': f, 'has_annotations': rel_path in annotations})

        files = sorted(files, key=itemgetter('file'))
        directories = sorted(directories, key=itemgetter('directory'))
        return files, directories


class AnnotateView(BaseView):
    template_name = 'web/annotate.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        code_directory = os.path.realpath(settings.CODE_DIRECTORY) + os.path.sep
        absolute_path = self.request.GET.get('path')
        if not absolute_path:
            return redirect(reverse('web:browse') + '?path=/')
        if not absolute_path.startswith('/'):
            raise Http404
        absolute_path = '.' + absolute_path
        absolute_path = os.path.join(settings.CODE_DIRECTORY, absolute_path)
        absolute_path = os.path.realpath(absolute_path)

        if not absolute_path.startswith(code_directory):
            raise Http404

        if not os.path.exists(absolute_path):
            raise Http404

        if not os.path.isfile(absolute_path):
            raise Http404

        relative_path = '/' + absolute_path[len(code_directory):]
        breadcrumbs = self.get_breadcrumbs(relative_path)

        annotations = {}
        for annotation in CodeAnnotation.objects.filter(path=relative_path):
            annotations[annotation.line_number] = {'user': annotation.user, 'annotation': annotation.annotation}

        with open(absolute_path) as f:
            code = f.read()

        try:
            lexer = get_lexer_for_filename(absolute_path)
        except ClassNotFound:
            lexer = TextLexer()
        code = highlight(code, lexer, Formatter(annotations=annotations, linenos='inline', linespans='line'))

        context.update({
            'code': code,
            'css': HtmlFormatter().get_style_defs('.highlight'),
            'relative_path': relative_path,
            'breadcrumbs': breadcrumbs,
        })
        return self.render_to_response(context)


class Formatter(HtmlFormatter):
    def __init__(self, annotations, **options):
        super(Formatter, self).__init__(**options)
        self.annotations = annotations

    def _wrap_linespans(self, inner):
        s = self.linespans
        i = self.linenostart - 1
        for t, line in inner:
            if t:
                i += 1
                if i in self.annotations:
                    annotation = self.annotations[i]
                    tooltip = '<span data-toggle="tooltip" data-placement="left" data-toggle="tooltip" ' + \
                              'title="{}: {}" class="annotation"><i class="fa fa-comment fa-fw"> </i> </span>'
                    tooltip = tooltip.format(annotation['user'].get_full_name(), annotation['annotation'])
                    yield 1, '<span id="%s-%d">%s%s</span>' % (s, i, tooltip, line)
                else:
                    yield 1, '<span id="%s-%d"><span class="fa fa-fw"></span> %s</span>' \
                          % (s, i, line)
            else:
                yield 0, line


class SubmitView(CreateView):
    model = CodeAnnotation
    fields = ('annotation', 'line_number', 'path')

    def form_valid(self, form):
        annotation = form.save(commit=False)
        annotation.user = self.request.user
        annotation.save()
        return redirect('{}?path={}#line-{}'.format(reverse('web:annotate'), annotation.path, annotation.line_number))

    def form_invalid(self, form):
        print(form.errors)

apps/web/templates/web/annotate.html
{% extends "web/base.html" %}

{% load i18n %}

{% block head %}
    <style>
        {{ css }}
        .highlight {
            margin-bottom: 200px;
        }
        .highlight pre > span {
            display: block;
            width: 100%;
            cursor: default;
        }
        .highlight pre > span.marked {
            background-color: #f8eec7;
        }
        #annotation-form {
            position: fixed;
            width: 360px;
        }
        #annotation-form textarea {
            width: 100%;
            height: 400px;
        }
    </style>
{% endblock head %}

{% block javascript %}
    <script type="text/javascript">
    $(function() {
        $('.highlight pre > span').click(function() {
            if ($(this).hasClass('marked')) {
                $(this).removeClass('marked')
            } else {
                $('.highlight pre > span').removeClass('marked');
                $(this).addClass('marked');
                $('input[name="line_number"]').attr('value', $(this).attr('id').slice(5));
            }
        });

        $('[data-toggle="tooltip"]').tooltip();
    });
    </script>
{% endblock %}

{% block content %}
    <div class="col-sm-{% if request.user.is_authenticated %}8{% else %}12{% endif %}">
        {{ code|safe }}
    </div>
    <div class="col-sm-4">
        {% if request.user.is_authenticated %}
        <div id="annotation-form">
        <form action="{% url 'web:submit' %}" method="post">
            {% csrf_token %}
            <textarea name="annotation" autocomplete="off" class="form-control form-group"></textarea>
            <input type="submit" value="{% trans "Save" %}" class="btn btn-default pull-right">
            <input type="hidden" value="{{ relative_path }}" name="path">
            <input type="hidden" value="" name="line_number">
        </form>
        </div>
        {% endif %}
    </div>
{% endblock content %}

apps/web/templates/web/base.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Code Annotate</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">

    {% block head %}{% endblock head %}
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'web:browse' %}?path=/">Code Annotate</a>
    </div>
  </div>
</nav>

<div class="container">
    <div class="row">
        {% if breadcrumbs %}
            <div class="col-sm-12">
                <ol class="breadcrumb">
                {% for breadcrumb in breadcrumbs %}
                    {% if not breadcrumb.name %}
                        {% if relative_path == '/' %}
                            <li class="active">{% trans "Root" %}</li>
                        {% else %}
                            <li><a href="{% url 'web:browse' %}?path=/">{% trans "Root" %}</a></li>
                        {% endif %}
                    {% elif forloop.last %}
                        <li class="active">{{ breadcrumb.name }}</li>
                    {% else %}
                        <li><a href="{% url 'web:browse' %}?path={{ breadcrumb.path }}">{{ breadcrumb.name }}</a></li>
                    {% endif %}
                {% endfor %}
                </ol>
            </div>
        {% endif %}

        {% block content %}{% endblock content %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
{% block javascript %}{% endblock javascript %}
</body>
</html>

apps/web/templates/web/browse.html
{% extends "web/base.html" %}

{% block content %}
    <div class="col-sm-12">
        <table class="table table-striped table-bordered">
        <tr>
            <td>
                <a href="{% url 'web:browse' %}?path={{ parent_directory }}">
                    <i class="fa fa-fw"></i>
                    <i class="fa fa-folder fa-fw"></i>
                    ..
                </a>
            </td>
        </tr>
        {% for directory in directories %}
            <tr>
                <td>
                    {% if directory.has_annotations %}
                        <i class="fa fa-comment fa-fw"></i>
                    {% else %}
                        <i class="fa fa-fw"></i>
                    {% endif %}
                    <a href="{% url 'web:browse' %}?path={{ relative_path }}{{ directory.directory }}">
                        <i class="fa fa-folder fa-fw"></i>
                        {{ directory.directory }}
                    </a>
                </td>
            </tr>
            {% endfor %}
            {% for file in files %}
            <tr>
                <td>
                    {% if file.has_annotations %}
                        <i class="fa fa-comment fa-fw"></i>
                    {% else %}
                        <i class="fa fa-fw"></i>
                    {% endif %}
                    <a href="{% url 'web:annotate' %}?path={{ relative_path }}{{ file.file }}">
                        <i class="fa fa-file fa-fw" style="color: #000000;"></i>
                        {{ file.file }}
                    </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}